//
//  ObjectClassifierModel.swift
//  ObjectClassifier
//
//  Created by Justin Bell on 12/28/25.
//

import Foundation
import CoreML

struct ClassifierModel {
    
    var url: URL
    
    func getModel() -> ObjectClassifierModel? {
        do {
            let config = MLModelConfiguration()
            let model = try ObjectClassifierModel(configuration: config)
            return model
        } catch {
            print("Error loading model: \(error)")
        }
        return nil
    }
    
//    func predict(image: CGImage) -> [String]? {
//        guard let model = getModel() else { return nil }
//        do {
//            let prediction = try model.prediction(image: image)
//            return prediction.classLabels
//        } catch {
//            print("Error predicting: \(error)")
//        }
//        return nil
//    }
    
//    func predict(pixelBuffer: CVPixelBuffer) -> [String]? {
//        guard let model = getModel() else { return nil }
//        do {
//            // Many autogenerated Core ML model classes expose a convenience prediction API like:
//            // prediction(image: CVPixelBuffer) -> ObjectClassifierModelOutput
//            // Try that first. If your model uses a different signature (e.g. imageWith:), adjust the label name below.
//            let output = try model.prediction(image: pixelBuffer)
//            // Commonly, classifiers expose either `classLabel` (String) and/or `classLabelProbs` ([String: Double])
//            // Return the top label as a single-element array for compatibility with the original method signature.
//            return [output.classLabel]
//        } catch {
//            print("Error during prediction: \(error)")
//            return nil
//        }
//    }
}
